---
#
# Prepare Catalina base directory
#
# If you are running multiple instances of Tomcat on a single host you should set CATALINA_BASE to be equal to the
# .../tomcat_instance1 or .../tomcat_instance2 directory as appropriate for each instance and the CATALINA_HOME
# environment variable to the common Tomcat installation whose files will be shared between the two instances.
# The CATALINA_BASE environment is optional if you are running a single Tomcat instance on the host and will
# default to CATALINA_HOME in that case. If you are running multiple instances as you are it should be provided.
# https://stackoverflow.com/questions/3090398/tomcat-catalina-base-and-catalina-home-variables#8584730

- name: create CATALINA_BASE directory
  file:
    path: "{{ tomcat_system_home }}{{ item.instance_name }}"
    state: directory
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
  with_items: "{{ tomcat_instance }}"

- name: create heapdumps directory
  file:
    path: "{{ tomcat_system_home }}{{ item.instance_name }}/heapdumps"
    state: directory
    owner: "{{ tomcat_root_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "u=rwx,g=rwx,o="
  with_items: "{{ tomcat_instance }}"

- name: create CATALINA_BASE/bin directory
  file:
    path: "{{ tomcat_system_home }}{{ item.instance_name }}/bin"
    state: directory
    owner: "{{ tomcat_root_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "u=rwx,g=rx,o="
  with_items: "{{ tomcat_instance }}"

- name: create CATALINA_BASE/conf directory
  file:
    path: "{{ tomcat_system_home }}{{ item.instance_name }}/conf"
    state: directory
    owner: "{{ tomcat_root_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "u=rwx,g=rx,o="
  with_items: "{{ tomcat_instance }}"

- name: create CATALINA_BASE/conf/Catalina directory
  file:
    path: "{{ tomcat_system_home }}{{ item.instance_name }}/conf/Catalina"
    state: directory
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "u=rwx,g=rx,o="
  with_items: "{{ tomcat_instance }}"

- name: create CATALINA_BASE/logs directories
  file:
    path: "{{ tomcat_system_home }}{{ item.1.instance_name }}/logs/"
    state: directory
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "{{ tomcat_catalina_logs_directory_mode }}"
  with_items:
    - "{{ tomcat_instance }}"

- name: create CATALINA_BASE/logs subdirectories
  file:
    path: "{{ tomcat_system_home }}{{ item.1.instance_name }}/logs/{{ item.0 }}"
    state: directory
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "{{ tomcat_catalina_logs_directory_mode }}"
  with_nested:
    - [ 'catalina', 'gc', 'access' ]
    - "{{ tomcat_instance }}"

- name: create CATALINA_BASE/lib directory
  file:
    path: "{{ tomcat_system_home }}{{ item.instance_name }}/lib"
    state: directory
    owner: "{{ tomcat_root_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "u=rwx,g=rx,o="
  with_items: "{{ tomcat_instance }}"

- name: create CATALINA_BASE/lib/ext directory
  file:
    path: "{{ tomcat_system_home }}{{ item.instance_name }}/lib/ext"
    state: directory
    owner: "{{ tomcat_root_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "u=rwx,g=rx,o="
  with_items: "{{ tomcat_instance }}"

- name: create CATALINA_BASE/shared/lib directory
  file:
    path: "{{ tomcat_system_home }}{{ item.instance_name }}/shared/lib"
    state: directory
    owner: "{{ tomcat_root_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "u=rwx,g=rx,o="
  with_items: "{{ tomcat_instance }}"

- name: create CATALINA_BASE/temp directory
  file:
    path: "{{ tomcat_system_home }}{{ item.instance_name }}/temp"
    state: directory
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "u=rwx,g=rwx,o="
  with_items: "{{ tomcat_instance }}"

- name: create CATALINA_BASE/webapps directory
  file:
    path: "{{ tomcat_system_home }}{{ item.instance_name }}/webapps"
    state: directory
    owner: "{{ tomcat_root_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "u=rwx,g=rwx,o="
  with_items: "{{ tomcat_instance }}"

- name: create CATALINA_BASE/work directory
  file:
    path: "{{ tomcat_system_home }}{{ item.instance_name }}/work"
    state: directory
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: "u=rwx,g=rwx,o="
  with_items: "{{ tomcat_instance }}"

- name: symlink catalina script
  file:
    src: "{{ tomcat_catalina_home }}/bin/catalina.sh"
    dest: "{{ tomcat_system_home }}{{ item.instance_name }}/bin/catalina.sh"
    state: link
    force: true
  with_items: "{{ tomcat_instance }}"

- name: symlink startup script
  file:
    src: "{{ tomcat_catalina_home }}/bin/startup.sh"
    dest: "{{ tomcat_system_home }}{{ item.instance_name }}/bin/startup.sh"
    state: link
    force: true
  with_items: "{{ tomcat_instance }}"

- name: symlink shutdown script
  file:
    src: "{{ tomcat_catalina_home }}/bin/shutdown.sh"
    dest: "{{ tomcat_system_home }}{{ item.instance_name }}/bin/shutdown.sh"
    state: link
    force: true
  with_items: "{{ tomcat_instance }}"

- name: 'generate configuartion from template, using the default recommended settings'
  template:
    src: '{{ item.0 }}.j2'
    dest: '{{ tomcat_system_home }}{{ item.1.instance_name }}/conf/{{ item.0 }}'
  with_nested:
    - [ 'context.xml', 'server.xml', 'web.xml', 'logging.properties', 'tomcat-users.xml' ]
    - "{{ tomcat_instance }}"
